### ISSUE TITLE
Schematic / Layout for Filament Sensor v2

### ISSUE THREAD

**Issue by piflixe** [Duet3D/FilamentMonitors#1]
Hi there! I can't find the schematic or layout files anywhere for the v2 of the laser filament sensor. 

Could someone please post the link the design files or push them here? kiCAD files would be sufficient, I can take care of PDF exports and the like.

Thank you so much!

**Comment by T3P3** [comment]
https://github.com/Duet3D/FilamentMonitors/blob/master/Filament_Monitor_Laser_v2.0/LaserFilamentMonitor_Schematic_v2.0.pdf

HTH

Tony

**Comment by piflixe** [comment]
Dear Tony @T3P3 ,
thank you so much for your quick reply! This is really helpful for me. I am trying to use the sensor and the whole sensor board for a different application, which looks really promising. Would you mind sharing the native design files (looks like kiCAD?) as well? I might need a board with more pins and a bigger processor so your design could be a good starting point. The plan is to release the results openSource as well so you might also benefit from it. If you do not want to push the files on github but would like to share them with me, please email to piela@konstruktiv-berlin.de
Thanks you!

**Comment by piflixe** [comment]
I hope I do not bother you with these questions, just keen to know and hoping to be able to free some pins on the sensor boards
- is the LDP pin on the ATtiny actually switched or just used as a power supply?
- did you include the voltage regulator so the whole board becomes 5V resistant? Or should it still be used with 3,3V only?

**Comment by T3P3** [comment]
They are in the latest commit (https://github.com/Duet3D/FilamentMonitors/commit/65b57c8e6b1f42bf2a952dd01901a3e57512fbc8).

Please so link to your new design files when its done 👍

**Comment by piflixe** [comment]
Thank you so much for the quick reaction @T3P3 !

This is our git repository: https://gitlab.com/konstruktiv_berlin/laser-motion-sensor

There is nothing working there yet, still work in progress. Only the LEDs are blinking and I added interrupt functionality for the v1.7 board to read STP/DIR pins. But hopefully it will be functional soon.
