### ISSUE TITLE
STL Files Corrupt

### ISSUE THREAD

**Issue by gamefanatic53** [Duet3D/FilamentMonitors#2]
LaserFilamentSensorHousing_DC42_new_base.stl
LaserFilamentSensorHousing_DC42_new_lid.stl
I will add the LaserFilamentMonitor_Schematic_v2.0.pdf won't open either.

These will no load into a slicer, or other application.  All state they are invalid.

**Comment by chrishamm** [comment]
It is properly displayed in the GitHub STL viewer so I am closing this issue.
